dist: xenial
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
install: pip install -r requirements.txt
script:
  - python -Wall -m unittest discover -t . -s dectest_test -p "*.py"
  - mypy dectest dectest_test
